import type {BrandKey} from './BrandSwitcher';

const pageImages:Record<BrandKey,Record<string,string>>={
 ampp:{about:'https://images.pexels.com/photos/8961623/pexels-photo-8961623.jpeg?auto=compress&cs=tinysrgb&w=2000',safety:'https://images.pexels.com/photos/34610698/pexels-photo-34610698.jpeg?auto=compress&cs=tinysrgb&w=2000',careers:'https://images.pexels.com/photos/159358/construction-site-build-construction-work-159358.jpeg?auto=compress&cs=tinysrgb&w=2000',contact:'https://images.pexels.com/photos/16368435/pexels-photo-16368435.jpeg?auto=compress&cs=tinysrgb&w=2000'},
 csr:{about:'https://images.pexels.com/photos/25537595/pexels-photo-25537595.jpeg?auto=compress&cs=tinysrgb&w=2000',safety:'https://images.pexels.com/photos/19879654/pexels-photo-19879654.jpeg?auto=compress&cs=tinysrgb&w=2000',careers:'https://images.pexels.com/photos/31460017/pexels-photo-31460017.jpeg?auto=compress&cs=tinysrgb&w=2000',contact:'https://images.pexels.com/photos/16368410/pexels-photo-16368410.jpeg?auto=compress&cs=tinysrgb&w=2000'},
 james:{about:'https://images.pexels.com/photos/35571322/pexels-photo-35571322.jpeg?auto=compress&cs=tinysrgb&w=2000',safety:'https://images.pexels.com/photos/9720534/pexels-photo-9720534.jpeg?auto=compress&cs=tinysrgb&w=2000',careers:'https://images.pexels.com/photos/5328573/pexels-photo-5328573.jpeg?auto=compress&cs=tinysrgb&w=2000',contact:'https://images.pexels.com/photos/17321815/pexels-photo-17321815.jpeg?auto=compress&cs=tinysrgb&w=2000'}
};
const names={ampp:'AMPP Construction',csr:'Collective Strategic Resources',james:'James Powerline Construction'};
const copy={
 ampp:{about:['Built around the people who do the work.','AMPP supports utility infrastructure with experienced field teams, practical execution and a commitment to the communities our work serves.'],safety:['Safety starts before the work does.','Our people come first. Training, accountability and consistent field practices help keep safety at the center of every project.'],careers:['Build work that matters.','Join a team supporting essential infrastructure, learning in the field and helping communities stay connected.']},
 csr:{about:['Complex work. Clear execution.','CSR brings coordinated teams and practical problem-solving to demanding infrastructure environments where communication and reliability matter.'],safety:['Prepared for demanding environments.','Safety is built into planning, coordination and field execution, with room for the certifications and program information each project requires.'],careers:['Bring your experience to the field.','Work alongside teams solving complex infrastructure challenges with a focus on coordination, responsiveness and dependable delivery.']},
 james:{about:['Powerline experience built in the field.','James Powerline Construction brings hands-on utility knowledge, responsive crews and dependable execution to essential electrical infrastructure.'],safety:['The standard behind every crew.','Safe work depends on preparation, training and accountability. Our approach keeps those expectations visible from planning through closeout.'],careers:['Build your future on the line.','Join experienced utility crews doing practical, essential work and building the skills that keep power infrastructure moving.']}
} as const;

export function StandardPage({brand,page}:{brand:BrandKey;page:'about'|'safety'|'careers'|'contact'}){
 const n=names[brand], img=pageImages[brand][page];
 if(page==='contact') return <div className="inner-page"><PageHero title="CONTACT" image={img}/><section className="contact-page"><div><p className="eyebrow"><i/>CONTACT {n.toUpperCase()}</p><h2>LET’S START A<br/>CONVERSATION.</h2><p>Have a project, field need or general question? Reach out to the team and we’ll help connect you with the right person.</p></div><div className="contact-details">{brand==='ampp'?<><div><small>ADDRESS</small><strong>810 W. Washington St.<br/>Winchester, IN 47394</strong></div><div><small>PHONE</small><strong>765-305-1988</strong></div><div><small>EMAIL</small><strong>Contact AMPP Construction</strong></div><div><small>IMMEDIATE SUPPORT</small><strong>765-546-2451</strong></div></>:<><div><small>GENERAL INQUIRIES</small><strong>Contact {n}</strong></div><div><small>PROJECT QUESTIONS</small><strong>Connect with our team</strong></div><div><small>LOCATION / PHONE</small><strong>Client content to be added</strong></div></>}</div></section></div>;
 const c=copy[brand][page];
 if(page==='careers') return <div className="inner-page"><PageHero title="JOIN OUR TEAM" image={img}/><section className="editorial-page"><div className="editorial-intro"><p className="eyebrow"><i/>CAREERS</p><h2>{c[0]}</h2><p>{c[1]}</p></div><div className="career-band"><div><small>OPPORTUNITIES</small><h3>Find your next role.</h3><p>Open positions and role details will be connected here once the client confirms the appropriate career system for this company.</p></div><a className="button career-button" href="#" onClick={e=>e.preventDefault()}>VIEW OPEN POSITIONS <span>→</span></a></div><div className="content-columns"><div><small>WHY JOIN US</small><h3>Work with purpose.</h3></div><div><p>Build experience on real infrastructure projects with teams that value safe work, practical knowledge and people who take pride in what they do.</p><p>Benefits, culture details and company-specific employment information can be added when final client content is available.</p></div></div></section></div>;
 return <div className="inner-page"><PageHero title={page==='about'?'ABOUT US':'SAFETY'} image={img}/><section className="editorial-page"><div className="editorial-intro"><p className="eyebrow"><i/>{page==='about'?'WHO WE ARE':'OUR COMMITMENT'}</p><h2>{c[0]}</h2><p>{c[1]}</p></div>{page==='about'?<><div className="content-columns"><div><small>OUR APPROACH</small><h3>Local knowledge. Broader support.</h3></div><div><p>Our teams are built around the realities of field work: experienced people, clear communication and dependable execution.</p><p>As part of the PowerGrid Services family, {n} can be supported by a broader network of infrastructure experience while maintaining its own operating identity.</p></div></div><div className="statement-band"><span>PEOPLE</span><span>FIELD EXPERIENCE</span><span>RELIABLE WORK</span></div></>:<><div className="safety-layout"><div><small>SAFETY INFORMATION</small><h3>Room for the details that matter.</h3><p>This page is intentionally designed to support substantial safety copy, training information, policies and changing certification details without turning them into a separate document library.</p></div><div className="badge-zone"><small>CERTIFICATIONS & BADGES</small><div className="badge-placeholders"><span>BADGE</span><span>BADGE</span><span>BADGE</span></div><p>Placeholder area for current company badges and certifications.</p></div></div><div className="content-columns"><div><small>TRAINING & ACCOUNTABILITY</small><h3>Safety is part of the work.</h3></div><div><p>Use this area for the client’s detailed safety program, training expectations, certifications and company-specific procedures.</p><p>Additional sections can expand naturally as final copy is provided, with imagery used selectively to keep a long page readable.</p></div></div></>}</section></div>;
}
function PageHero({title,image}:{title:string;image:string}){return <section className="inner-hero"><img src={image} alt=""/><div className="inner-hero-shade"/><h1>{title}</h1></section>}
